[package]
name = "gremlin-watcher"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
crossbeam-channel.workspace = true
notify.workspace = true
walkdir.workspace = true
tracing.workspace = true
directories.workspace = true
serde.workspace = true
serde_json.workspace = true
quick-xml.workspace = true

[lints]
workspace = true
